### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by twindan** [syncsketch/python-api#1]
The code as is only currently supports Python 2.  Python 2 will be out of support in about 3 months, so many people have migrated to Python 3.

It will install ok on Python 3, but you cannot import the module.  

Trying to directly load "syncsketch.py" shows some of the problems -- you use print() without parentheses which is no longer support in Python 3.

**Comment by soccer99** [comment]
I have just pushed a fix for python3 to the master branch!  Please pull the new library code and give it a try!
