### ISSUE TITLE
inconsistent naming convention

### ISSUE THREAD

**Issue by janikotterbach** [syncsketch/python-api#6]
Inconsistent naming convention for example:

https://github.com/syncsketch/python-api/blob/2a6764a83a11aca3403d05e693029a16546a35df/syncsketch/syncsketch.py#L166
https://github.com/syncsketch/python-api/blob/2a6764a83a11aca3403d05e693029a16546a35df/syncsketch/syncsketch.py#L176
https://github.com/syncsketch/python-api/blob/2a6764a83a11aca3403d05e693029a16546a35df/syncsketch/syncsketch.py#L467

**Comment by soccer99** [comment]
This is fixed.
