### ISSUE TITLE
Using dictionary as default value for keyword argument can give strange result

### ISSUE THREAD

**Issue by larsbijl** [syncsketch/python-api#7]
At several points in the API uses `{}` as the argument. 

https://stackoverflow.com/questions/5712904/empty-dictionary-as-default-value-for-keyword-argument-in-python-function-dicti

This could give inconsistent behavior for end-users.

**Comment by soccer99** [comment]
This is late but I'm pushing these fixes in the next release.  Thank you for flagging!
